### ISSUE TITLE
Nm

### ISSUE THREAD

**Issue by Bart-0110** [uyjulian/LiteModWDL#3]
Nm

**Comment by Pokechu22** [comment]
That is, partially, the purpose of that file.  However, it's also there to get some other info from the server (such as entity ranges).  It's also like that so that it's disableable if need be (though right now, need not be).  (And most plugins that try to restrict WDL don't use that system; they use client brand or loaded liteloader mod sniffing).

That system's actually being updated over time (it'll be much cleaner in 1.8d, whenever that comes out).
