### ISSUE TITLE
Make it an option to not notify the servers of downloading the worlds

### ISSUE THREAD

**Issue by Pangamma** [uyjulian/LiteModWDL#5]
Kind of pissing me off that this is the only game in town for world downloading, and it can be easily stopped by server side plugins. 

I've been trying to edit the source on this so that this mod doesn't send data to the servers that allow servers to prevent access to the server when this plugin is installed. Since I have never built a MCP or liteloader mod, I'm not 100% familiar with the ofuckated compile process. So instead I've been trying to use dependency injection and bytecode manipulation. Five hours of my time wasted on bytecode manipulation manuals, test injection projects, dependency injection tutorials. I contemplated throwing all kinds of things out of windows over here. I've had it. This is really vexing me right now. 

Could you guys please create a mod file that doesn't try to activate or use the plugin channels? It's a long shot question, but at this point I may as well try asking.

**Comment by Pangamma** [comment]
Make it a premium option, idc. Five or ten bucks for this.

**Comment by uyjulian** [comment]
Liteloader sends mod lists to the server anyway.

So even if you stop this mod sending plugin data, Liteloader will still send data to the server (unless you use the coremod version)

**Comment by Pokechu22** [comment]
I'm not going to publicly release a version, and won't do a premium one (that just seems wrong).  But I will say that it isn't hard to change this if you actually look at the code - it's one class.  Still, MCP is a pain sometimes (but if you just get everything in the right place, and don't deal with simlinks, instead just copying the `src/wdl` folder into `mcp/src/minecraft` after decompiling, it gets easier).

The system is supposed to balance the mod - it's super powerful and in some cases can be used maliciously.  My _goal_ is to have the system where if a server disables the mod, there's a form for requesting it to be re-enabled within the mod itself, plus systems to allow downloading in specific chunks (EG, say, land owned by your faction or your own skyblock island).  I have most of that already implemented in beta versions.

The problem is that to implement a system like this, you _need_ to, at minimum, send a [`REGISTER`](http://wiki.vg/Plugin_channel#REGISTER) packet (otherwise Bukkit will not allow sending it).  I opted to send a second packet so that permissions would only be sent when downloading finishes - EG when changing dimensions; however, this has led to plugins that kick players (and that annoys me; that wasn't the way the system was supposed to be used).

It's a complicated system, and I think apart from plugins that are kicking players, it works fairly well (and will work better once I get permission requests finished).  

May I ask: What type of server are you on (minigames, creative, factions, etc...), what specifically do you plan to do with the download, and are you being affected by a plugin that is kicking you, or one that is using the in-mod control options?

**Comment by Pokechu22** [comment]
I'll put it another way.  People will try (with varying levels of success) to block World Downloader anyways, and thus it's better to provide a built-in way that is (or can be) less restrictive, rather than forcing people to write plugins that kick players.
